#!/bin/bash

read -p "Enter Email: " email
read -p "Enter full name: " name
read -p "Enter apartment number: " apptNumber
read -p "Enter monthly rent: " rent
read -p "Enter next due date: " date
 accountBalance=$rent
cd Data
if [ -n "$(find ~/CS3423/assignments/1assign/Data -name "$email" -mmin -5)" ]; then
    echo "Error. File already exist"
 else
        cat > $email <<EOF
	"$email $name"
       	"$apptNumber $rent $accountBalance $date"
EOF
fi
cd ..
